apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mikkena
      app.kubernetes.io/component: mikkena
      app.kubernetes.io/instance: mikkena
    name: mikkena
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: mikkena
    template:
      metadata:
        labels:
          deploymentconfig: mikkena
      spec:
        containers:
        - image: mikkena
          imagePullPolicy: Always
          name: mikkena
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mikkena
        from:
          kind: ImageStreamTag
          name: mikkena:test
      type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: mikkena
      app.kubernetes.io/component: mikkena
      app.kubernetes.io/instance: mikkena
    name: mikkena
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: mikkena
      app.kubernetes.io/component: mikkena
      app.kubernetes.io/instance: mikkena
    name: mikkena
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: mikkena
      weight: 100
    wildcardPolicy: None
